version: "3.4"

services:
  backend:
    volumes:
      - ../../backend:/backend/
    command: "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True

  worker:
    volumes:
      - ../../backend:/backend/
    environment:
      - DEBUG=True

  scheduler:
    volumes:
      - ../../backend:/backend/
    environment:
      - DEBUG=True

  frontend:
    build:
      target: build_stage
    command: "npm run start"
    ports:
      - "3000:3000"
    volumes:
      - ../../frontend/src:/app/src
    env_file:
      - ./.env
    environment:
      - REACT_APP_API_DOMAIN=$DEV_API_DOMAIN
      - REACT_APP_AUTH_DOMAIN=$DEV_API_DOMAIN
      - REACT_APP_API_PROTOCOL=http
