# Generated by Django 3.0.2 on 2020-01-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aac', models.CharField(max_length=20)),
                ('request_number', models.CharField(max_length=255)),
            ],
        ),
    ]