# Generated by Django 3.0.4 on 2020-03-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solo_rog_api', '0002_addresstype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=4, unique=True)),
                ('desc', models.CharField(blank=True, max_length=40)),
            ],
        ),
    ]
