# Generated by Django 3.0.4 on 2020-03-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solo_rog_api', '0002_addresstype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nsn', models.CharField(max_length=13, null=True, unique=True)),
                ('nomen', models.CharField(max_length=50, null=True)),
                ('uom', models.CharField(max_length=5, null=True)),
                ('price', models.IntegerField(null=True)),
                ('sac', models.IntegerField(null=True)),
                ('serial_control_flag', models.CharField(max_length=2, null=True)),
                ('lot_control_flag', models.CharField(max_length=2, null=True)),
                ('recoverability_code', models.CharField(max_length=2, null=True)),
                ('shelf_life_code', models.IntegerField(null=True)),
                ('controlled_inv_item_code', models.CharField(max_length=2, null=True)),
            ],
        ),
    ]
