# Generated by Django 3.0.4 on 2020-03-10 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solo_rog_api', '0003_dic'),
        ('solo_rog_api', '0003_part'),
    ]

    operations = [
    ]
