# Generated by Django 3.0.4 on 2020-03-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solo_rog_api', '0004_merge_20200310_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_request', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
