# Generated by Django 3.0.4 on 2020-03-11 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solo_rog_api', '0005_servicerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuppAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('desc', models.CharField(blank=True, max_length=40)),
            ],
        ),
    ]
