# Generated by Django 3.0.4 on 2020-03-11 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solo_rog_api', '0006_suppadd'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('desc', models.CharField(blank=True, max_length=40)),
                ('suppadd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subinventorys', to='solo_rog_api.SuppAdd')),
            ],
        ),
    ]
