# Generated by Django 3.0.4 on 2020-03-12 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solo_rog_api', '0009_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_date', models.DateTimeField()),
                ('key_and_transmit_date', models.DateTimeField(blank=True, null=True)),
                ('esd', models.DateField(blank=True, null=True)),
                ('projected_qty', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('received_qty', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solo_rog_api.Dic')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='solo_rog_api.Document')),
            ],
        ),
    ]
