# Generated by Django 3.0.4 on 2020-03-12 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solo_rog_api', '0010_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='solo_rog_api.Document'),
        ),
    ]
