# Generated by Django 3.0.4 on 2020-03-13 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solo_rog_api', '0011_auto_20200312_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ric', models.CharField(max_length=20)),
                ('addy1', models.CharField(blank=True, max_length=50, null=True)),
                ('addy2', models.CharField(blank=True, max_length=50, null=True)),
                ('addy3', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zip', models.CharField(blank=True, max_length=11, null=True)),
                ('country', models.CharField(blank=True, max_length=15, null=True)),
                ('address_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='solo_rog_api.AddressType')),
                ('document', models.ManyToManyField(blank=True, related_name='addresses', to='solo_rog_api.Document')),
            ],
        ),
    ]
