# Generated by Django 3.0.4 on 2020-03-14 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solo_rog_api', '0012_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
