# Generated by Django 3.0.4 on 2020-03-20 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solo_rog_api', '0013_delete_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-sdn']},
        ),
    ]
