# Generated by Django 3.0.4 on 2020-03-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solo_rog_api', '0014_auto_20200320_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='received_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
