# Generated by Django 3.0.4 on 2020-04-09 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solo_rog_api', '0019_userinwarehouse_warehouse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinwarehouse',
            options={'default_related_name': 'warehouse_membership', 'ordering': ['user__username']},
        ),
        migrations.AlterField(
            model_name='userinwarehouse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userinwarehouse',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_membership', to='solo_rog_api.Warehouse'),
        ),
    ]
